-- Seed realistic dummy complaints with before & after photos, GPS locations, and fulfillment ratings

INSERT INTO complaints (
    society_id, 
    resident_id, 
    category_id, 
    title, 
    description, 
    location_details, 
    photo_url, 
    priority, 
    status, 
    assigned_staff_id, 
    resolution_notes, 
    resolution_photo_url, 
    sla_deadline, 
    sla_breached, 
    escalated, 
    version, 
    created_at, 
    updated_at, 
    resolved_at
) VALUES 
(
    1, 
    2, 
    1, 
    'Major Bathroom Pipe Burst & Water Leakage', 
    'High pressure water leak from main flush pipe causing water pooling on master bathroom floor.', 
    '📍 GPS: 28.6139, 77.2090 • Flat A-101 Master Bathroom', 
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80', 
    'HIGH', 
    'RESOLVED', 
    3, 
    'Replaced worn-out rubber coupling gasket and sealed high-pressure joint with heavy duty brass fitting. Leak test passed cleanly.', 
    'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80', 
    CURRENT_TIMESTAMP + INTERVAL '2 hours', 
    FALSE, 
    FALSE, 
    1, 
    CURRENT_TIMESTAMP - INTERVAL '3 hours', 
    CURRENT_TIMESTAMP - INTERVAL '1 hour', 
    CURRENT_TIMESTAMP - INTERVAL '1 hour'
),
(
    1, 
    2, 
    2, 
    'Block B Passenger Elevator #2 Jerking & Noisy', 
    'Elevator #2 making loud grinding noise when ascending between 3rd and 4th floors. Needs urgent mechanical check.', 
    '📍 GPS: 28.6145, 77.2098 • Block B Elevator Shaft #2', 
    'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=600&q=80', 
    'HIGH', 
    'IN_PROGRESS', 
    4, 
    NULL, 
    NULL, 
    CURRENT_TIMESTAMP + INTERVAL '1 hour', 
    FALSE, 
    FALSE, 
    0, 
    CURRENT_TIMESTAMP - INTERVAL '1 hour', 
    CURRENT_TIMESTAMP - INTERVAL '30 minutes', 
    NULL
),
(
    1, 
    2, 
    3, 
    'Main Gate Security Cabin MCB Board Sparking', 
    'Sparking sound and burning plastic smell coming from security cabin main distribution box.', 
    '📍 GPS: 28.6150, 77.2105 • Main Security Gate Cabin', 
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80', 
    'HIGH', 
    'ASSIGNED', 
    4, 
    NULL, 
    NULL, 
    CURRENT_TIMESTAMP + INTERVAL '2 hours', 
    FALSE, 
    FALSE, 
    0, 
    CURRENT_TIMESTAMP - INTERVAL '20 minutes', 
    CURRENT_TIMESTAMP - INTERVAL '10 minutes', 
    NULL
),
(
    1, 
    2, 
    4, 
    'Clubhouse Swimming Pool Side Waste Bin Overflowing', 
    'Waste bin near pool sunbeds is full. Please arrange cleaning staff.', 
    '📍 GPS: 28.6132, 77.2085 • Clubhouse Pool Deck Area', 
    'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=600&q=80', 
    'LOW', 
    'OPEN', 
    NULL, 
    NULL, 
    NULL, 
    CURRENT_TIMESTAMP + INTERVAL '24 hours', 
    FALSE, 
    FALSE, 
    0, 
    CURRENT_TIMESTAMP - INTERVAL '10 minutes', 
    CURRENT_TIMESTAMP - INTERVAL '10 minutes', 
    NULL
);

-- Seed 5-Star Feedback Rating for Resolved Complaint #1
INSERT INTO feedback_ratings (complaint_id, resident_id, rating, review)
VALUES (1, 2, 5, 'Outstanding prompt service! Plumber arrived within 25 minutes, replaced the damaged valve, and cleaned the area.')
ON CONFLICT (complaint_id) DO NOTHING;
